const quizData=[{question:"Q1 介護報酬の審査・支払業務は、実際には誰が行っている？",choices:["市町村が直接審査","国民健康保険団体連合会に委託","都道府県が代行"],answer:1,explanation:"正解は②。市町村が保険者ですが、実務は国保連に委託されています。①と混同しやすい頻出ポイントです。"},{question:"Q2 償還払いとは？",choices:["事業者が保険者に直接請求","利用者がいったん全額支払い、後から保険給付分の払い戻しを受ける","現物給付のみ"],answer:1,explanation:"正解は②。福祉用具購入費・住宅改修費などは、原則として償還払い方式です。"},{question:"Q3 区分支給限度基準額を超えて利用者が使いたい場合、市町村が独自に上乗せできる仕組みは？",choices:["種類支給限度基準額","区分支給限度基準額の上乗せ","市町村特別給付"],answer:1,explanation:"正解は②。区分限度額の上乗せは市町村の裁量で可能です。③の市町村特別給付とは別物です。"},{question:"Q4 特定のサービス種類について、市町村が独自に上限を設定できる制度は？",choices:["種類支給限度基準額","区分支給限度基準額","支給限度額の一元管理"],answer:0,explanation:"正解は①。地域のサービス提供体制に応じて、種類ごとに限度額を設定できます。"},{question:"Q5 市町村特別給付の財源は？",choices:["第1号保険料","第2号保険料","国庫負担"],answer:0,explanation:"正解は①。市町村特別給付は第1号被保険者の保険料のみで賄われます。国庫負担や第2号保険料は使えません。"},{question:"Q6 交通事故などの第三者行為による給付調整（求償事務）は誰が委託先？",choices:["都道府県","国民健康保険団体連合会","国民健康保険中央会"],answer:1,explanation:"正解は②。介護報酬審査支払と同じく、国保連への委託業務です。"},{question:"Q7 居宅サービス計画の作成を依頼する窓口を設置するのは？",choices:["都道府県","市町村（保険者）","国保連"],answer:1,explanation:"正解は②。ケアプラン作成依頼の受付窓口設置は市町村の事務です。"}];
const screens={study:document.querySelector("#study-screen"),quiz:document.querySelector("#quiz-screen"),result:document.querySelector("#result-screen")};
const startQuizButton=document.querySelector("#start-quiz"),backStudyButton=document.querySelector("#back-study"),nextQuestionButton=document.querySelector("#next-question"),retryQuizButton=document.querySelector("#retry-quiz"),reviewVideoButton=document.querySelector("#review-video"),questionCount=document.querySelector("#question-count"),scoreText=document.querySelector("#score"),progressBar=document.querySelector("#progress-bar"),questionText=document.querySelector("#question-text"),choicesElement=document.querySelector("#choices"),feedback=document.querySelector("#feedback"),resultScore=document.querySelector("#result-score"),resultMessage=document.querySelector("#result-message");
let currentQuestion=0,score=0,answered=false;
function showScreen(name){Object.values(screens).forEach(function(screen){screen.classList.remove("screen-active")});screens[name].classList.add("screen-active")}
function startQuiz(){currentQuestion=0;score=0;answered=false;showScreen("quiz");renderQuestion()}
function renderQuestion(){const item=quizData[currentQuestion];answered=false;questionText.textContent=item.question;questionCount.textContent=String(currentQuestion+1)+" / "+String(quizData.length);scoreText.textContent=String(score)+"点";progressBar.style.width=String(currentQuestion/quizData.length*100)+"%";feedback.className="feedback";feedback.textContent="";nextQuestionButton.disabled=true;nextQuestionButton.textContent=currentQuestion===quizData.length-1?"結果を見る":"次へ";choicesElement.replaceChildren();item.choices.forEach(function(choice,index){const button=document.createElement("button");button.className="choice-button";button.type="button";button.textContent=["①","②","③"][index]+" "+choice;button.addEventListener("click",function(){selectAnswer(index)});choicesElement.append(button)})}
function selectAnswer(selectedIndex){if(answered)return;answered=true;const item=quizData[currentQuestion];const buttons=[...choicesElement.querySelectorAll(".choice-button")];const isCorrect=selectedIndex===item.answer;if(isCorrect)score+=1;buttons.forEach(function(button,index){button.disabled=true;if(index===item.answer)button.classList.add("correct");if(index===selectedIndex&&!isCorrect)button.classList.add("wrong")});scoreText.textContent=String(score)+"点";feedback.className="feedback show "+(isCorrect?"correct":"wrong");feedback.textContent=(isCorrect?"正解！":"惜しい！")+" "+item.explanation;nextQuestionButton.disabled=false}
function goNext(){if(!answered)return;currentQuestion+=1;if(currentQuestion>=quizData.length){showResult();return}renderQuestion()}
function showResult(){progressBar.style.width="100%";showScreen("result");resultScore.textContent=String(score)+" / "+String(quizData.length);resultMessage.textContent=score===quizData.length?"満点です。国保連、市町村特別給付、支給限度額の違いまでしっかり入っています。":"解説を見直すと、混同しやすいところがかなり整理できます。もう一周すると定着しやすいです。"}
startQuizButton.addEventListener("click",startQuiz);nextQuestionButton.addEventListener("click",goNext);retryQuizButton.addEventListener("click",startQuiz);backStudyButton.addEventListener("click",function(){showScreen("study")});reviewVideoButton.addEventListener("click",function(){showScreen("study")});
